### PR TITLE
More features

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by nuttycom — CHANGES_REQUESTED** [review]
tested bug:
```
λ ./build-wallet-dag.sh
Traceback (most recent call last):
  File "/home/nuttycom/work/zcash-developers/./zcash-issue-dag.py", line 490, in <module>
    main()
  File "/home/nuttycom/work/zcash-developers/./zcash-issue-dag.py", line 323, in main
    terminate_at = set([(reverse_repos[tuple(r.split('/', 1))], int(i)) for (r, i) in terminate_at])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nuttycom/work/zcash-developers/./zcash-issue-dag.py", line 323, in <listcomp>
    terminate_at = set([(reverse_repos[tuple(r.split('/', 1))], int(i)) for (r, i) in terminate_at])
                                                                            ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/developers/compare/f2a71e892a0cf408ecc552dd3d76065f4f9e1e9b..547dfa4d24b83766a08a489c8210b9d20c550dd2) to fix the bug. `set(x)` takes `x` as an iterable, and strings are natively iterable in Python.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/developers/compare/547dfa4d24b83766a08a489c8210b9d20c550dd2..af0fc94cdf9ee1828fc963f18fd5114ed3362a29) to also strip whitespace from the comma-separated values.

**Review by nuttycom — APPROVED** [review]
tested ACK

**Pull request merged**
